version: '3'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:${DATABASE_PORT}"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: yarn dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - db
